# This is a basic workflow to help you get started with Actions

name: azure_function_github_action

env:
  # ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
  # ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
  # ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
  # ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}
  IMAGE_TAG: ${{ github.sha }}

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  push:
    branches:
      - master

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./node-function-app
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4

      # - name: "Login via Azure CLI"
      #   uses: azure/login@v1
      #   with:
      #     creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: "Docker Login"
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build Docker image
        run: docker build -t prasadreddy2349/node-function-app:${{env.IMAGE_TAG}} .

      - name: Push Docker image
        run: docker push prasadreddy2349/node-function-app:${{env.IMAGE_TAG}}

      # - name: Build and push
      #   uses: docker/build-push-action@v3
      #   with:
      #     context: ./node-function-app
      #     push: true
      #     tags: prasadreddy2349/node-function-app/${{env.IMAGE_TAG}}

      # - name: "Run Azure Functions Container Action"
      #   uses: Azure/functions-container-action@v1
      #   id: fa
      #   with:
      #     app-name: PLEASE_REPLACE_THIS_WITH_YOUR_FUNCTION_APP_NAME
      #     image: REGISTRY/NAMESPACE/IMAGE:TAG
